In [1]:
import pandas as pd

In [2]:
heartratedata = pd.read_csv("heart_attack_prediction_dataset.csv")

In [3]:
heartratedata

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,MSV9918,60,Male,121,94/76,61,1,1,1,0,...,10.806373,235420,19.655895,67,7,7,Thailand,Asia,Northern Hemisphere,0
8759,QSV6764,28,Female,120,157/102,73,1,0,0,1,...,3.833038,217881,23.993866,617,4,9,Canada,North America,Northern Hemisphere,0
8760,XKA5925,47,Male,250,161/75,105,0,1,1,1,...,2.375214,36998,35.406146,527,4,4,Brazil,South America,Southern Hemisphere,1
8761,EPE6801,36,Male,178,119/67,60,1,0,1,0,...,0.029104,209943,27.294020,114,2,8,Brazil,South America,Southern Hemisphere,0
8762,ZWN9666,25,Female,356,138/67,75,1,1,0,0,...,9.005234,247338,32.914151,180,7,4,United Kingdom,Europe,Northern Hemisphere,1

In [6]:
def missing_values_percent(dataframe):
    missing_values = dataframe.isna().sum()
    percentage_missing = (missing_values / len(dataframe) * 100).round(2)
    result_movie = pd.DataFrame({'Missing Values': missing_values, "Percentage": percentage_missing})
    result_movie["Percentage"] = result_movie["Percentage"].astype(str) + '%'
    
    return result_movie

result = missing_values_percent(heartratedata)
result

                                 Missing Values Percentage
Patient ID                                    0       0.0%
Age                                           0       0.0%
Sex                                           0       0.0%
Cholesterol                                   0       0.0%
Blood Pressure                                0       0.0%
Heart Rate                                    0       0.0%
Diabetes                                      0       0.0%
Family History                                0       0.0%
Smoking                                       0       0.0%
Obesity                                       0       0.0%
Alcohol Consumption                           0       0.0%
Exercise Hours Per Week                       0       0.0%
Diet                                          0       0.0%
Previous Heart Problems                       0       0.0%
Medication Use                                0       0.0%
Stress Level                                  0       0.0%
Sedentary Hours Per Day                       0       0.0%
Income                                        0       0.0%
BMI                                           0       0.0%
Triglycerides                                 0       0.0%
Physical Activity Days Per Week               0       0.0%
Sleep Hours Per Day                           0       0.0%
Country                                       0       0.0%
Continent                                     0       0.0%
Hemisphere                                    0       0.0%
Heart Attack Risk                             0       0.0%

In [16]:
hearratedata = heartratedata.drop(["Patient ID", "Family History", "Alcohol Consumption", "Exercise Hours Per Week", "Diet", "Previous Heart Problems", "Medication Use"], axis=1)

In [19]:
hearratedata.head()

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Smoking,Obesity,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,67,Male,208,158/88,72,0,1,0,9,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,21,Male,389,165/93,98,1,1,1,1,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,21,Female,324,174/99,72,1,0,0,9,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,84,Male,383,163/100,73,1,1,0,9,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,66,Male,318,91/88,93,1,1,1,6,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0

In [20]:
hearratedata

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Smoking,Obesity,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,67,Male,208,158/88,72,0,1,0,9,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,21,Male,389,165/93,98,1,1,1,1,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,21,Female,324,174/99,72,1,0,0,9,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,84,Male,383,163/100,73,1,1,0,9,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,66,Male,318,91/88,93,1,1,1,6,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,60,Male,121,94/76,61,1,1,0,8,10.806373,235420,19.655895,67,7,7,Thailand,Asia,Northern Hemisphere,0
8759,28,Female,120,157/102,73,1,0,1,8,3.833038,217881,23.993866,617,4,9,Canada,North America,Northern Hemisphere,0
8760,47,Male,250,161/75,105,0,1,1,5,2.375214,36998,35.406146,527,4,4,Brazil,South America,Southern Hemisphere,1
8761,36,Male,178,119/67,60,1,1,0,5,0.029104,209943,27.294020,114,2,8,Brazil,South America,Southern Hemisphere,0
8762,25,Female,356,138/67,75,1,0,0,8,9.005234,247338,32.914151,180,7,4,United Kingdom,Europe,Northern Hemisphere,1

In [21]:
heartratedata = hearratedata

In [22]:
heartratedata

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Smoking,Obesity,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,67,Male,208,158/88,72,0,1,0,9,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,21,Male,389,165/93,98,1,1,1,1,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,21,Female,324,174/99,72,1,0,0,9,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,84,Male,383,163/100,73,1,1,0,9,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,66,Male,318,91/88,93,1,1,1,6,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,60,Male,121,94/76,61,1,1,0,8,10.806373,235420,19.655895,67,7,7,Thailand,Asia,Northern Hemisphere,0
8759,28,Female,120,157/102,73,1,0,1,8,3.833038,217881,23.993866,617,4,9,Canada,North America,Northern Hemisphere,0
8760,47,Male,250,161/75,105,0,1,1,5,2.375214,36998,35.406146,527,4,4,Brazil,South America,Southern Hemisphere,1
8761,36,Male,178,119/67,60,1,1,0,5,0.029104,209943,27.294020,114,2,8,Brazil,South America,Southern Hemisphere,0
8762,25,Female,356,138/67,75,1,0,0,8,9.005234,247338,32.914151,180,7,4,United Kingdom,Europe,Northern Hemisphere,1

In [23]:
heartratedata = heartratedata.drop(["Stress Level", "Sedentary Hours Per Day", "Income", "Triglycerides", "Country", "Continent", "Hemisphere"], axis=1)

In [24]:
heartratedata

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Smoking,Obesity,BMI,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk
0,67,Male,208,158/88,72,0,1,0,31.251233,0,6,0
1,21,Male,389,165/93,98,1,1,1,27.194973,1,7,0
2,21,Female,324,174/99,72,1,0,0,28.176571,4,4,0
3,84,Male,383,163/100,73,1,1,0,36.464704,3,4,0
4,66,Male,318,91/88,93,1,1,1,21.809144,1,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8758,60,Male,121,94/76,61,1,1,0,19.655895,7,7,0
8759,28,Female,120,157/102,73,1,0,1,23.993866,4,9,0
8760,47,Male,250,161/75,105,0,1,1,35.406146,4,4,1
8761,36,Male,178,119/67,60,1,1,0,27.294020,2,8,0
8762,25,Female,356,138/67,75,1,0,0,32.914151,7,4,1

In [25]:
gender_mapping = {"Male": 0, "Female": 1}
heartratedata["Sex"] = heartratedata["Sex"].map(gender_mapping)

In [26]:
heartratedata

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Smoking,Obesity,BMI,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk
0,67,0,208,158/88,72,0,1,0,31.251233,0,6,0
1,21,0,389,165/93,98,1,1,1,27.194973,1,7,0
2,21,1,324,174/99,72,1,0,0,28.176571,4,4,0
3,84,0,383,163/100,73,1,1,0,36.464704,3,4,0
4,66,0,318,91/88,93,1,1,1,21.809144,1,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8758,60,0,121,94/76,61,1,1,0,19.655895,7,7,0
8759,28,1,120,157/102,73,1,0,1,23.993866,4,9,0
8760,47,0,250,161/75,105,0,1,1,35.406146,4,4,1
8761,36,0,178,119/67,60,1,1,0,27.294020,2,8,0
8762,25,1,356,138/67,75,1,0,0,32.914151,7,4,1

In [27]:
type(heartratedata["BMI"])

pandas.core.series.Series

In [32]:
import numpy as np

bmi = heartratedata["BMI"]

cond_list = [bmi < 18.5, bmi < 25, bmi < 30, bmi >= 30]
choice_list = [1, 2, 3, 4]

heartratedata["BMI_cat"] = np.select(cond_list, choice_list)

In [33]:
heartratedata.head()

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Smoking,Obesity,BMI,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk,BMI_cat
0,67,0,208,158/88,72,0,1,0,31.251233,0,6,0,4
1,21,0,389,165/93,98,1,1,1,27.194973,1,7,0,3
2,21,1,324,174/99,72,1,0,0,28.176571,4,4,0,3
3,84,0,383,163/100,73,1,1,0,36.464704,3,4,0,4
4,66,0,318,91/88,93,1,1,1,21.809144,1,5,0,2

In [34]:
heartratedata["Blood Pressure"]

0        158/88
1        165/93
2        174/99
3       163/100
4         91/88
         ...
8758      94/76
8759    157/102
8760     161/75
8761     119/67
8762     138/67
Name: Blood Pressure, Length: 8763, dtype: object

In [35]:
type(heartratedata["Blood Pressure"])

pandas.core.series.Series

In [37]:
bldp = list(heartratedata["Blood Pressure"])

In [38]:
bldp

['158/88',
 '165/93',
 '174/99',
 '163/100',
 '91/88',
 '172/86',
 '102/73',
 '131/68',
 '144/105',
 '160/70',
 '107/69',
 '158/71',
 '101/72',
 '169/72',
 '112/81',
 '114/88',
 '173/75',
 '120/74',
 '120/100',
 '160/98',
 '180/101',
 '130/84',
 '175/60',
 '173/109',
 '161/90',
 '140/95',
 '148/105',
 '160/76',
 '113/78',
 '99/81',
 '120/77',
 '178/72',
 '111/91',
 '99/85',
 '103/107',
 '94/60',
 '127/109',
 '134/60',
 '115/92',
 '124/93',
 '104/96',
 '144/108',
 '101/90',
 '115/109',
 '149/73',
 '120/63',
 '106/106',
 '102/76',
 '114/92',
 '124/93',
 '173/108',
 '173/109',
 '168/91',
 '159/79',
 '100/80',
 '118/76',
 '103/83',
 '152/90',
 '151/85',
 '144/98',
 '109/95',
 '92/61',
 '179/93',
 '120/69',
 '161/108',
 '131/76',
 '107/65',
 '132/109',
 '131/97',
 '149/73',
 '177/99',
 '130/94',
 '174/93',
 '110/105',
 '116/98',
 '139/107',
 '164/76',
 '104/83',
 '118/86',
 '122/77',
 '109/74',
 '160/70',
 '92/65',
 '151/101',
 '95/78',
 '115/73',
 '148/94',
 '100/66',
 '163/110',
 '122/80',
 '118/91',
 '110/104',
 '149/83',
 '134/100',
 '116/85',
 '165/79',
 '102/69',
 '168/107',
 '160/67',
 '92/71',
 '164/65',
 '155/104',
 '104/98',
 '159/76',
 '152/94',
 '108/78',
 '168/90',
 '105/108',
 '146/94',
 '109/65',
 '166/89',
 '163/61',
 '117/76',
 '106/60',
 '159/70',
 '145/92',
 '170/106',
 '134/94',
 '113/80',
 '163/102',
 '149/100',
 '125/76',
 '100/67',
 '110/101',
 '149/69',
 '135/63',
 '137/67',
 '178/78',
 '116/73',
 '110/72',
 '100/88',
 '121/72',
 '174/102',
 '177/94',
 '126/108',
 '120/101',
 '118/105',
 '142/88',
 '128/105',
 '143/75',
 '103/78',
 '116/102',
 '132/76',
 '169/92',
 '113/79',
 '99/71',
 '96/93',
 '145/82',
 '173/62',
 '179/62',
 '100/69',
 '153/77',
 '156/74',
 '162/82',
 '98/109',
 '165/89',
 '150/73',
 '163/102',
 '134/90',
 '133/60',
 '157/110',
 '96/106',
 '173/82',
 '96/92',
 '162/71',
 '91/83',
 '148/89',
 '145/98',
 '180/108',
 '98/67',
 '154/81',
 '172/64',
 '118/75',
 '144/60',
 '133/63',
 '154/102',
 '123/91',
 '102/82',
 '146/76',
 '178/83',
 '123/72',
 '154/63',
 '158/85',
 '161/105',
 '131/70',
 '169/90',
 '154/95',
 '110/104',
 '121/65',
 '142/104',
 '153/89',
 '125/95',
 '135/92',
 '143/83',
 '149/73',
 '96/66',
 '157/98',
 '120/109',
 '171/69',
 '106/101',
 '90/105',
 '133/77',
 '179/88',
 '177/70',
 '98/73',
 '174/61',
 '176/110',
 '167/62',
 '103/82',
 '171/75',
 '158/87',
 '131/109',
 '124/94',
 '164/71',
 '100/81',
 '164/90',
 '108/64',
 '179/63',
 '141/75',
 '116/93',
 '115/78',
 '146/107',
 '102/105',
 '151/95',
 '133/82',
 '134/72',
 '157/104',
 '126/107',
 '105/103',
 '168/110',
 '162/71',
 '115/87',
 '99/64',
 '126/109',
 '99/90',
 '123/107',
 '165/71',
 '127/89',
 '121/66',
 '159/98',
 '165/70',
 '138/89',
 '119/91',
 '102/107',
 '97/93',
 '120/65',
 '118/82',
 '178/86',
 '92/82',
 '111/69',
 '164/92',
 '137/109',
 '154/92',
 '91/62',
 '155/104',
 '124/91',
 '125/72',
 '159/108',
 '106/64',
 '103/106',
 '162/62',
 '105/80',
 '175/70',
 '125/93',
 '98/108',
 '123/95',
 '133/102',
 '157/100',
 '110/67',
 '142/96',
 '133/91',
 '128/94',
 '115/109',
 '175/62',
 '155/110',
 '95/63',
 '161/94',
 '117/76',
 '179/82',
 '179/65',
 '96/77',
 '167/64',
 '142/68',
 '138/66',
 '180/103',
 '90/62',
 '137/64',
 '163/84',
 '158/108',
 '151/68',
 '168/97',
 '156/106',
 '103/75',
 '103/61',
 '105/103',
 '173/65',
 '116/74',
 '131/96',
 '141/68',
 '99/108',
 '121/96',
 '110/96',
 '112/66',
 '133/70',
 '171/99',
 '96/100',
 '180/92',
 '142/67',
 '156/75',
 '162/67',
 '90/100',
 '109/107',
 '168/68',
 '146/100',
 '108/75',
 '145/62',
 '168/68',
 '112/108',
 '150/95',
 '122/97',
 '161/77',
 '115/61',
 '92/105',
 '100/89',
 '96/60',
 '137/100',
 '94/109',
 '93/102',
 '114/103',
 '105/90',
 '90/78',
 '126/74',
 '177/75',
 '179/104',
 '101/75',
 '172/86',
 '173/63',
 '177/95',
 '93/62',
 '171/65',
 '91/68',
 '175/77',
 '143/83',
 '165/78',
 '163/63',
 '124/88',
 '99/82',
 '166/86',
 '165/78',
 '145/65',
 '158/76',
 '132/76',
 '163/106',
 '126/84',
 '107/83',
 '137/72',
 '111/109',
 '114/80',
 '160/61',
 '169/60',
 '111/76',
 '151/69',
 '146/84',
 '139/99',
 '162/79',
 '95/74',
 '148/87',
 '114/88',
 '117/64',
 '90/103',
 '159/87',
 '114/60',
 '147/91',
 '178/106',
 '99/83',
 '139/106',
 '165/103',
 '178/104',
 '162/66',
 '162/73',
 '161/79',
 '148/82',
 '155/65',
 '171/67',
 '162/101',
 '160/107',
 '158/92',
 '139/69',
 '167/74',
 '101/67',
 '112/109',
 '165/91',
 '97/78',
 '141/104',
 '103/72',
 '132/103',
 '141/78',
 '146/90',
 '177/66',
 '120/84',
 '119/72',
 '101/87',
 '140/80',
 '157/101',
 '91/61',
 '121/73',
 '172/80',
 '131/67',
 '125/64',
 '100/104',
 '101/106',
 '140/89',
 '108/104',
 '98/96',
 '133/64',
 '116/82',
 '168/69',
 '177/87',
 '153/81',
 '103/96',
 '114/62',
 '95/64',
 '99/60',
 '169/67',
 '92/107',
 '175/67',
 '131/67',
 '123/106',
 '171/75',
 '92/108',
 '162/75',
 '163/96',
 '158/60',
 '118/72',
 '113/108',
 '177/103',
 '124/81',
 '104/108',
 '147/97',
 '160/69',
 '175/72',
 '159/82',
 '163/98',
 '108/104',
 '179/81',
 '152/75',
 '138/82',
 '101/64',
 '115/100',
 '108/103',
 '140/88',
 '164/96',
 '175/104',
 '111/108',
 '160/98',
 '152/107',
 '142/63',
 '158/67',
 '96/96',
 '122/89',
 '145/63',
 '143/108',
 '131/91',
 '132/103',
 '140/82',
 '134/100',
 '129/94',
 '138/79',
 '167/108',
 '117/89',
 '93/108',
 '131/101',
 '142/107',
 '112/75',
 '128/92',
 '117/98',
 '156/103',
 '96/66',
 '104/102',
 '145/96',
 '94/62',
 '176/97',
 '112/71',
 '153/83',
 '94/86',
 '136/83',
 '125/78',
 '105/96',
 '168/105',
 '142/93',
 '157/62',
 '141/102',
 '161/63',
 '176/77',
 '162/91',
 '167/103',
 '101/84',
 '116/80',
 '141/85',
 '151/60',
 '121/95',
 '90/72',
 '99/94',
 '143/67',
 '171/70',
 '178/105',
 '139/100',
 '170/89',
 '177/94',
 '151/76',
 '117/90',
 '133/83',
 '135/107',
 '178/99',
 '131/108',
 '156/68',
 '150/65',
 '130/85',
 '115/73',
 '153/61',
 '104/65',
 '96/96',
 '111/70',
 '129/66',
 '159/84',
 '140/63',
 '105/87',
 '109/99',
 '172/107',
 '157/83',
 '157/80',
 '150/82',
 '174/75',
 '158/66',
 '173/81',
 '118/79',
 '92/80',
 '135/64',
 '148/85',
 '113/72',
 '133/92',
 '126/100',
 '100/96',
 '114/62',
 '108/76',
 '100/105',
 '138/105',
 '157/109',
 '154/66',
 '138/101',
 '153/89',
 '154/91',
 '171/94',
 '157/84',
 '130/97',
 '168/91',
 '101/90',
 '105/75',
 '163/102',
 '167/93',
 '166/92',
 '109/82',
 '139/105',
 '170/91',
 '117/98',
 '165/98',
 '108/67',
 '159/102',
 '126/91',
 '164/86',
 '134/103',
 '116/60',
 '126/61',
 '180/93',
 '148/87',
 '122/100',
 '179/104',
 '111/94',
 '94/81',
 '135/93',
 '112/89',
 '171/108',
 '110/71',
 '170/62',
 '164/80',
 '126/74',
 '150/90',
 '102/105',
 '119/102',
 '135/78',
 '149/105',
 '174/60',
 '176/93',
 '116/99',
 '93/108',
 '165/69',
 '110/91',
 '129/66',
 '171/90',
 '162/110',
 '111/99',
 '153/88',
 '136/71',
 '163/94',
 '128/97',
 '127/91',
 '103/69',
 '135/89',
 '125/63',
 '164/108',
 '92/62',
 '138/82',
 '115/61',
 '115/74',
 '147/94',
 '169/104',
 '175/105',
 '118/80',
 '94/88',
 '142/72',
 '160/70',
 '143/88',
 '106/64',
 '115/63',
 '104/81',
 '101/98',
 '97/62',
 '91/79',
 '143/88',
 '136/64',
 '143/96',
 '138/64',
 '128/71',
 '161/65',
 '135/71',
 '117/96',
 '133/95',
 '109/60',
 '91/79',
 '116/102',
 '117/90',
 '129/62',
 '166/63',
 '147/90',
 '146/82',
 '107/105',
 '156/90',
 '166/86',
 '118/64',
 '158/98',
 '101/91',
 '137/99',
 '98/90',
 '167/85',
 '132/65',
 '129/87',
 '122/79',
 '119/71',
 '117/100',
 '155/65',
 '95/90',
 '159/62',
 '108/79',
 '178/105',
 '120/90',
 '126/78',
 '94/73',
 '98/105',
 '96/85',
 '173/76',
 '141/82',
 '100/68',
 '118/67',
 '154/77',
 '110/60',
 '169/70',
 '180/98',
 '161/98',
 '156/74',
 '109/106',
 '143/108',
 '142/75',
 '167/90',
 '172/61',
 '172/78',
 '135/90',
 '126/69',
 '128/103',
 '121/108',
 '151/95',
 '91/93',
 '115/103',
 '93/66',
 '104/107',
 '164/84',
 '160/78',
 '161/81',
 '93/100',
 '174/99',
 '140/97',
 '156/61',
 '144/72',
 '171/69',
 '176/91',
 '159/63',
 '92/71',
 '120/77',
 '151/108',
 '123/88',
 '117/89',
 '103/69',
 '105/82',
 '163/81',
 '117/63',
 '91/92',
 '145/61',
 '133/69',
 '174/90',
 '130/72',
 '107/70',
 '165/92',
 '130/63',
 '124/94',
 '173/110',
 '168/76',
 '129/102',
 '141/96',
 '130/65',
 '105/103',
 '115/80',
 '121/110',
 '145/73',
 '140/99',
 '160/61',
 '178/64',
 '119/110',
 '177/82',
 '103/92',
 '161/99',
 '180/78',
 '138/96',
 '180/95',
 '117/103',
 '110/76',
 '134/65',
 '175/71',
 '126/105',
 '120/88',
 '133/110',
 '104/107',
 '131/82',
 '176/77',
 '120/62',
 '165/110',
 '137/104',
 '158/107',
 '100/87',
 '107/67',
 '102/83',
 '158/108',
 '116/83',
 '101/63',
 '107/101',
 '169/110',
 '159/63',
 '164/60',
 '134/106',
 '115/85',
 '170/67',
 '141/95',
 '180/98',
 '106/109',
 '124/103',
 '94/107',
 '144/94',
 '123/60',
 '117/61',
 '153/102',
 '134/107',
 '106/70',
 '144/91',
 '122/94',
 '156/69',
 '172/99',
 '138/107',
 '162/102',
 '131/102',
 '97/90',
 '175/70',
 '98/71',
 '104/71',
 '144/66',
 '123/105',
 '170/92',
 '131/66',
 '166/100',
 '128/104',
 '102/79',
 '104/90',
 '92/71',
 '170/83',
 '111/104',
 '132/98',
 '139/96',
 '178/62',
 '98/74',
 '116/73',
 '121/84',
 '95/80',
 '116/89',
 '109/66',
 '138/82',
 '150/94',
 '168/61',
 '142/63',
 '154/62',
 '176/96',
 '97/104',
 '171/90',
 '100/107',
 '99/76',
 '150/107',
 '130/64',
 '132/93',
 '97/96',
 '180/80',
 '129/66',
 '164/86',
 '111/83',
 '107/68',
 '149/85',
 '102/93',
 '105/67',
 '132/93',
 '92/104',
 '157/83',
 '113/102',
 '103/107',
 '105/100',
 '146/103',
 '100/96',
 '143/97',
 '134/81',
 '157/80',
 '116/85',
 '118/96',
 '103/105',
 '136/86',
 '148/88',
 '117/63',
 '114/88',
 '166/69',
 '119/76',
 '128/92',
 '173/75',
 '141/89',
 '139/66',
 '121/68',
 '162/86',
 '95/90',
 '165/73',
 '158/60',
 '95/65',
 '93/91',
 '101/93',
 '123/97',
 '122/86',
 '166/93',
 '148/89',
 '108/72',
 '126/69',
 '178/105',
 '142/101',
 '115/60',
 '162/90',
 '104/73',
 '140/71',
 '173/64',
 '152/101',
 '166/60',
 '148/69',
 '176/72',
 '149/69',
 '170/99',
 '96/82',
 '100/60',
 '127/103',
 '152/109',
 '121/94',
 '113/63',
 '159/78',
 '131/76',
 '162/66',
 '180/62',
 '154/96',
 '95/107',
 '92/71',
 '141/60',
 '121/88',
 '151/66',
 '148/88',
 '166/103',
 '101/77',
 '162/96',
 '133/82',
 '96/76',
 '170/75',
 '108/110',
 '151/88',
 '104/73',
 '170/95',
 '115/81',
 '172/81',
 '169/86',
 '141/88',
 '92/76',
 '163/68',
 '166/70',
 '155/82',
 '137/110',
 '158/98',
 '158/108',
 '173/94',
 '173/88',
 '118/63',
 '174/87',
 '133/98',
 '158/68',
 '177/109',
 '165/86',
 '91/62',
 '118/99',
 '169/69',
 '127/73',
 '162/81',
 '139/96',
 '147/74',
 '151/94',
 '147/65',
 '162/89',
 '97/100',
 '161/92',
 '124/90',
 '154/67',
 '136/74',
 '170/101',
 '160/108',
 '92/96',
 '134/84',
 '152/82',
 '101/61',
 '152/101',
 '177/107',
 '148/64',
 '167/78',
 '102/65',
 '90/69',
 '163/106',
 '154/100',
 '164/104',
 '122/76',
 '96/86',
 '172/90',
 '172/100',
 '103/100',
 '100/91',
 '105/99',
 '179/101',
 '168/110',
 '113/91',
 '144/108',
 '170/87',
 '139/77',
 '108/77',
 '174/72',
 '159/91',
 '143/82',
 '135/83',
 '141/105',
 '173/98',
 '107/84',
 '91/84',
 '99/105',
 '168/102',
 '153/103',
 '107/98',
 '120/87',
 '161/109',
 '140/65',
 '141/65',
 '94/74',
 '103/90',
 '114/110',
 '118/78',
 '103/93',
 '109/76',
 '172/85',
 '147/108',
 '118/69',
 '141/84',
 ...]

In [39]:
type(bldp)

list

In [45]:
bldpList = []
systolicbp = []
diastolicbp = []

for data in bldp:
    tempdata = data.split("/")
    systolicbp.append(tempdata[0])
    diastolicbp.append(tempdata[1])

In [46]:
len(systolicbp)

8763

In [53]:
len(diastolicbp)
type(systolicbp[0])

str

In [54]:
bprankList = []

def getRange1(num):
    if num >= 130 and num <= 139:
        return True
    
def getRange2(num):
    if num >= 80 and num <= 89:
        return True

for i in range(0, len(diastolicbp)):
    if int(systolicbp[i]) < 120 and int(diastolicbp[i]) < 80:
        bprankList.append(1)
    elif int(systolicbp[i]) >= 120 and int(systolicbp[i]) <= 129 and int(diastolicbp[i]) < 80:
        bprankList.append(2)
    elif getRange1(int(systolicbp[i])) or getRange2(int(diastolicbp[i])):
        bprankList.append(3)
    elif int(systolicbp[i]) >= 140 or int(diastolicbp[i]) >= 90:
        bprankList.append(4)

len(bprankList)

8763

In [55]:
bprankList

[3,
 4,
 4,
 4,
 3,
 3,
 1,
 3,
 4,
 4,
 1,
 4,
 1,
 4,
 3,
 3,
 4,
 2,
 4,
 4,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 3,
 2,
 4,
 4,
 3,
 4,
 1,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 1,
 3,
 4,
 3,
 4,
 4,
 1,
 4,
 2,
 4,
 3,
 1,
 3,
 3,
 4,
 4,
 3,
 4,
 4,
 4,
 3,
 4,
 3,
 3,
 2,
 1,
 4,
 1,
 4,
 1,
 1,
 4,
 1,
 4,
 3,
 4,
 4,
 3,
 3,
 3,
 4,
 1,
 4,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 1,
 3,
 4,
 1,
 1,
 4,
 4,
 4,
 3,
 3,
 4,
 4,
 2,
 1,
 4,
 4,
 3,
 3,
 4,
 1,
 1,
 3,
 2,
 4,
 4,
 4,
 4,
 4,
 3,
 4,
 4,
 1,
 4,
 3,
 4,
 1,
 1,
 4,
 3,
 4,
 4,
 1,
 4,
 4,
 3,
 4,
 3,
 4,
 4,
 3,
 3,
 4,
 4,
 3,
 4,
 4,
 3,
 3,
 4,
 4,
 1,
 3,
 4,
 1,
 4,
 3,
 4,
 4,
 3,
 4,
 3,
 2,
 4,
 3,
 4,
 3,
 4,
 4,
 4,
 2,
 4,
 3,
 4,
 3,
 3,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 4,
 1,
 4,
 4,
 4,
 3,
 4,
 3,
 3,
 4,
 4,
 3,
 4,
 1,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 3,
 1,
 4,
 4,
 4,
 4,
 3,
 2,
 4,
 4,
 3,
 4,
 4,
 4,
 2,
 3,
 3,
 3,
 1,
 4,
 3,
 4,
 1,
 4,
 4,
 2,
 4,
 1,
 4,
 4,
 3,
 4,
 4,
 4,
 4,
 3,
 4,
 1,
 4,
 3,
 4,
 4,
 4,
 4,
 1,
 4,
 1,
 3,
 4,
 1,
 4,
 4,
 3,
 4,
 1,
 3,
 3,
 4,
 4,
 4,
 4,
 1,
 1,
 4,
 4,
 1,
 3,
 4,
 4,
 4,
 4,
 1,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 3,
 1,
 3,
 4,
 4,
 4,
 4,
 1,
 2,
 4,
 4,
 1,
 3,
 4,
 4,
 1,
 4,
 1,
 4,
 3,
 4,
 4,
 3,
 3,
 3,
 4,
 4,
 4,
 3,
 4,
 3,
 3,
 3,
 4,
 3,
 4,
 4,
 1,
 4,
 3,
 3,
 4,
 1,
 3,
 3,
 1,
 4,
 3,
 1,
 4,
 4,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 3,
 4,
 1,
 4,
 4,
 1,
 4,
 1,
 3,
 4,
 4,
 4,
 3,
 1,
 3,
 3,
 4,
 1,
 2,
 3,
 3,
 2,
 4,
 4,
 3,
 4,
 4,
 3,
 3,
 4,
 3,
 3,
 4,
 1,
 1,
 1,
 4,
 4,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 3,
 4,
 4,
 4,
 4,
 3,
 4,
 4,
 3,
 4,
 3,
 1,
 4,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 4,
 4,
 3,
 3,
 3,
 3,
 4,
 3,
 4,
 3,
 4,
 3,
 4,
 1,
 4,
 4,
 4,
 1,
 4,
 4,
 1,
 4,
 1,
 3,
 3,
 3,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 4,
 4,
 1,
 4,
 4,
 4,
 4,
 3,
 3,
 4,
 4,
 4,
 3,
 3,
 4,
 3,
 4,
 4,
 3,
 1,
 4,
 1,
 4,
 1,
 2,
 3,
 4,
 3,
 4,
 4,
 3,
 3,
 3,
 4,
 4,
 3,
 1,
 3,
 3,
 3,
 1,
 3,
 4,
 4,
 1,
 1,
 4,
 3,
 4,
 4,
 3,
 3,
 4,
 4,
 3,
 3,
 4,
 4,
 1,
 4,
 4,
 4,
 3,
 3,
 4,
 4,
 4,
 1,
 4,
 4,
 3,
 3,
 1,
 2,
 4,
 3,
 4,
 4,
 4,
 3,
 3,
 3,
 4,
 1,
 4,
 3,
 2,
 4,
 4,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 4,
 4,
 4,
 3,
 3,
 4,
 4,
 4,
 1,
 3,
 2,
 4,
 1,
 3,
 1,
 1,
 4,
 4,
 4,
 3,
 3,
 4,
 4,
 3,
 1,
 1,
 3,
 4,
 1,
 1,
 3,
 3,
 4,
 3,
 2,
 4,
 3,
 4,
 3,
 1,
 1,
 4,
 4,
 2,
 4,
 4,
 3,
 4,
 4,
 3,
 1,
 4,
 4,
 3,
 4,
 3,
 3,
 3,
 2,
 1,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 2,
 1,
 4,
 3,
 4,
 3,
 1,
 1,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 2,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 3,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 2,
 4,
 3,
 3,
 1,
 3,
 3,
 1,
 4,
 4,
 3,
 4,
 3,
 1,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 3,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 4,
 4,
 4,
 3,
 4,
 4,
 1,
 3,
 4,
 4,
 3,
 3,
 4,
 3,
 4,
 2,
 4,
 3,
 4,
 3,
 1,
 3,
 4,
 3,
 1,
 4,
 4,
 4,
 4,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 1,
 4,
 3,
 1,
 4,
 4,
 4,
 4,
 3,
 4,
 3,
 4,
 4,
 1,
 1,
 4,
 4,
 4,
 3,
 4,
 4,
 1,
 4,
 1,
 3,
 4,
 3,
 3,
 4,
 1,
 1,
 3,
 3,
 3,
 1,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 3,
 3,
 4,
 3,
 2,
 3,
 3,
 1,
 3,
 4,
 1,
 3,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 4,
 4,
 3,
 3,
 1,
 3,
 4,
 1,
 4,
 4,
 3,
 3,
 2,
 3,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 3,
 4,
 3,
 1,
 2,
 4,
 4,
 1,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 1,
 4,
 4,
 4,
 1,
 4,
 3,
 4,
 4,
 4,
 4,
 1,
 4,
 3,
 4,
 3,
 4,
 1,
 4,
 3,
 1,
 4,
 4,
 3,
 1,
 4,
 3,
 3,
 3,
 3,
 1,
 4,
 4,
 3,
 3,
 4,
 4,
 4,
 3,
 1,
 3,
 3,
 4,
 4,
 3,
 1,
 4,
 4,
 2,
 3,
 3,
 4,
 4,
 4,
 3,
 4,
 4,
 4,
 4,
 3,
 4,
 4,
 4,
 3,
 3,
 1,
 4,
 4,
 4,
 4,
 1,
 1,
 4,
 4,
 4,
 2,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 1,
 4,
 4,
 3,
 3,
 4,
 4,
 3,
 3,
 4,
 4,
 4,
 4,
 3,
 4,
 4,
 4,
 1,
 4,
 4,
 1,
 4,
 1,
 3,
 4,
 1,
 3,
 ...]

In [56]:
heartratedata["BPrank"] = bprankList

In [57]:
heartratedata

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Smoking,Obesity,BMI,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk,BMI_cat,BPrank
0,67,0,208,158/88,72,0,1,0,31.251233,0,6,0,4,3
1,21,0,389,165/93,98,1,1,1,27.194973,1,7,0,3,4
2,21,1,324,174/99,72,1,0,0,28.176571,4,4,0,3,4
3,84,0,383,163/100,73,1,1,0,36.464704,3,4,0,4,4
4,66,0,318,91/88,93,1,1,1,21.809144,1,5,0,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,60,0,121,94/76,61,1,1,0,19.655895,7,7,0,2,1
8759,28,1,120,157/102,73,1,0,1,23.993866,4,9,0,2,4
8760,47,0,250,161/75,105,0,1,1,35.406146,4,4,1,4,4
8761,36,0,178,119/67,60,1,1,0,27.294020,2,8,0,3,1
8762,25,1,356,138/67,75,1,0,0,32.914151,7,4,1,4,3

In [61]:
# Age, Cholestrol, Heart Rate
AgeMean = np.mean(list(heartratedata["Age"]))
AgeStd = np.std(list(heartratedata["Age"]))
ChoMean = np.mean(list(heartratedata["Cholesterol"]))
ChoStd = np.std(list(heartratedata["Cholesterol"]))
HRMean = np.mean(list(heartratedata["Heart Rate"]))
HRStd = np.std(list(heartratedata["Heart Rate"]))

In [62]:
def getNormal(mean, std, arr):
    tempArr = []
    for data in arr:
        temp = (data - mean) / std
        tempArr.append(temp)
    return tempArr

AgeNormalList = getNormal(AgeMean, AgeStd, list(heartratedata["Age"]))
ChoNormalList = getNormal(ChoMean, ChoStd, list(heartratedata["Cholesterol"]))
HRNormalList = getNormal(HRMean, HRStd, list(heartratedata["Heart Rate"]))

AgeNormalList

[0.6255571310253205,
 -1.5393223174717747,
 -1.5393223174717747,
 1.4256212750351165,
 0.5784945343188619,
 0.013743373841358786,
 1.707996855273868,
 1.4256212750351165,
 -1.5863849141782334,
 -0.5039451899296857,
 0.907932711264072,
 0.8138075178511549,
 1.0961830980899063,
 0.29611895408011035,
 1.613871661860951,
 0.907932711264072,
 0.7196823244382377,
 -0.7392581734619788,
 -0.17450701298447557,
 0.29611895408011035,
 0.5784945343188619,
 -0.40981999651676854,
 -0.17450701298447557,
 1.4256212750351165,
 -0.8333833668748959,
 1.707996855273868,
 -0.26863220639739277,
 -0.6451329800490615,
 1.1903082915028236,
 0.4373067441994861,
 -1.2569467372330232,
 -1.3510719306459404,
 -1.2569467372330232,
 1.5197464684480337,
 -0.5510077866361444,
 -0.0803818195715584,
 -1.2569467372330232,
 -1.162821543820106,
 0.6255571310253205,
 -1.162821543820106,
 -1.1157589471136475,
 -0.31569480310385134,
 1.5197464684480337,
 -0.45688259322322716,
 -0.17450701298447557,
 -0.9745711569942717,
 -0.127444416278017,
 0.7667449211446963,
 1.4726838717415751,
 -1.068696350407189,
 0.10786856725427597,
 -0.8333833668748959,
 0.7667449211446963,
 0.6255571310253205,
 -1.068696350407189,
 -1.398134527352399,
 0.013743373841358786,
 0.7667449211446963,
 0.9549953079705307,
 0.8608701145576134,
 0.060805970547817376,
 -0.5510077866361444,
 1.707996855273868,
 -1.3040093339394818,
 -0.03331922286509981,
 0.4373067441994861,
 -0.36275739981030997,
 0.15493116396073456,
 -1.068696350407189,
 0.9549953079705307,
 0.4373067441994861,
 -0.36275739981030997,
 -1.492259720765316,
 -0.03331922286509981,
 1.707996855273868,
 0.060805970547817376,
 -1.1157589471136475,
 0.907932711264072,
 0.6255571310253205,
 -0.8804459635813545,
 -0.40981999651676854,
 -0.6921955767555201,
 -0.03331922286509981,
 1.707996855273868,
 0.7196823244382377,
 -1.1157589471136475,
 -0.7392581734619788,
 0.10786856725427597,
 0.4373067441994861,
 1.2373708882092822,
 0.29611895408011035,
 0.7196823244382377,
 1.0961830980899063,
 0.5314319376124033,
 -0.36275739981030997,
 1.378558678328658,
 -1.2569467372330232,
 -1.068696350407189,
 1.3314960816221995,
 -1.2098841405265646,
 1.707996855273868,
 -0.6921955767555201,
 -0.6451329800490615,
 1.5197464684480337,
 0.10786856725427597,
 -1.633447510884692,
 0.8608701145576134,
 1.2373708882092822,
 -0.03331922286509981,
 -1.5393223174717747,
 1.707996855273868,
 -1.2098841405265646,
 0.7196823244382377,
 0.907932711264072,
 0.5784945343188619,
 1.0020579046769893,
 -1.1157589471136475,
 -1.492259720765316,
 1.613871661860951,
 1.707996855273868,
 1.1903082915028236,
 0.4373067441994861,
 -1.2569467372330232,
 -1.6805101075911506,
 0.29611895408011035,
 -0.927508560287813,
 0.29611895408011035,
 -0.7863207701684373,
 0.8138075178511549,
 1.613871661860951,
 1.6609342585674096,
 -0.9745711569942717,
 -0.6451329800490615,
 -1.162821543820106,
 1.6609342585674096,
 -0.7863207701684373,
 1.3314960816221995,
 1.5197464684480337,
 0.8138075178511549,
 -1.0216337537007303,
 -0.22156960969093417,
 -0.927508560287813,
 0.4373067441994861,
 -1.4451971240588577,
 0.9549953079705307,
 -0.9745711569942717,
 0.24905635737365175,
 -0.0803818195715584,
 0.39024414749302755,
 0.4843693409059447,
 1.2373708882092822,
 -1.0216337537007303,
 1.3314960816221995,
 -0.40981999651676854,
 -1.2098841405265646,
 0.3431815507865689,
 -0.8333833668748959,
 -1.1157589471136475,
 0.013743373841358786,
 0.7667449211446963,
 1.049120501383448,
 -0.5980703833426029,
 -0.45688259322322716,
 -1.2569467372330232,
 -0.40981999651676854,
 1.049120501383448,
 -1.2569467372330232,
 0.39024414749302755,
 0.7196823244382377,
 -0.5510077866361444,
 -0.5510077866361444,
 0.6255571310253205,
 1.1903082915028236,
 -1.633447510884692,
 -0.8804459635813545,
 -1.4451971240588577,
 -0.5980703833426029,
 1.5668090651544924,
 -0.8333833668748959,
 0.4373067441994861,
 -1.2569467372330232,
 0.24905635737365175,
 1.6609342585674096,
 1.613871661860951,
 1.6609342585674096,
 1.2373708882092822,
 1.2844334849157408,
 -0.8804459635813545,
 1.4256212750351165,
 -1.5393223174717747,
 1.0020579046769893,
 0.29611895408011035,
 -0.03331922286509981,
 0.5784945343188619,
 1.0020579046769893,
 0.20199376066719316,
 -1.3510719306459404,
 -1.162821543820106,
 1.4726838717415751,
 -1.398134527352399,
 1.143245694796365,
 -1.0216337537007303,
 -1.6805101075911506,
 -0.22156960969093417,
 -0.5510077866361444,
 1.378558678328658,
 0.20199376066719316,
 -0.9745711569942717,
 -1.398134527352399,
 -1.492259720765316,
 -0.17450701298447557,
 0.907932711264072,
 0.4373067441994861,
 -1.398134527352399,
 0.8608701145576134,
 0.20199376066719316,
 -0.7863207701684373,
 -0.40981999651676854,
 -1.398134527352399,
 1.2844334849157408,
 -0.22156960969093417,
 -1.2098841405265646,
 -1.492259720765316,
 -1.3510719306459404,
 -1.4451971240588577,
 0.3431815507865689,
 -0.31569480310385134,
 -0.36275739981030997,
 1.3314960816221995,
 -0.0803818195715584,
 1.613871661860951,
 -1.5393223174717747,
 -0.31569480310385134,
 1.3314960816221995,
 -0.40981999651676854,
 1.0020579046769893,
 1.5197464684480337,
 -1.5863849141782334,
 -1.068696350407189,
 0.29611895408011035,
 0.5314319376124033,
 1.4256212750351165,
 -0.5510077866361444,
 0.39024414749302755,
 0.10786856725427597,
 0.10786856725427597,
 -0.17450701298447557,
 0.20199376066719316,
 -1.1157589471136475,
 -1.0216337537007303,
 0.7196823244382377,
 -0.5039451899296857,
 0.10786856725427597,
 -0.6921955767555201,
 1.5197464684480337,
 1.0961830980899063,
 1.0961830980899063,
 -1.6805101075911506,
 -1.3040093339394818,
 -0.0803818195715584,
 -0.7863207701684373,
 0.6255571310253205,
 0.29611895408011035,
 -1.2098841405265646,
 1.2844334849157408,
 1.5668090651544924,
 -0.17450701298447557,
 0.39024414749302755,
 0.672619727731779,
 -1.5393223174717747,
 -1.398134527352399,
 -0.45688259322322716,
 -1.3510719306459404,
 1.049120501383448,
 1.378558678328658,
 -0.5039451899296857,
 -0.45688259322322716,
 -0.5039451899296857,
 -1.492259720765316,
 -0.7392581734619788,
 -0.03331922286509981,
 1.5197464684480337,
 0.672619727731779,
 -0.31569480310385134,
 1.0020579046769893,
 -0.45688259322322716,
 -1.6805101075911506,
 -0.127444416278017,
 1.2844334849157408,
 1.0020579046769893,
 0.29611895408011035,
 -0.40981999651676854,
 0.4373067441994861,
 -0.17450701298447557,
 0.9549953079705307,
 -1.162821543820106,
 0.907932711264072,
 1.4726838717415751,
 1.143245694796365,
 1.049120501383448,
 -0.36275739981030997,
 0.10786856725427597,
 0.9549953079705307,
 0.4843693409059447,
 -1.3040093339394818,
 -0.6451329800490615,
 -1.633447510884692,
 -1.6805101075911506,
 -0.03331922286509981,
 0.4373067441994861,
 -0.8333833668748959,
 0.6255571310253205,
 -0.17450701298447557,
 0.4843693409059447,
 1.0020579046769893,
 -1.3040093339394818,
 1.707996855273868,
 0.7667449211446963,
 -1.398134527352399,
 1.0961830980899063,
 1.3314960816221995,
 1.4726838717415751,
 -1.3510719306459404,
 0.6255571310253205,
 1.0961830980899063,
 -0.6921955767555201,
 0.29611895408011035,
 0.013743373841358786,
 0.29611895408011035,
 -0.8333833668748959,
 -0.5980703833426029,
 1.5668090651544924,
 -1.0216337537007303,
 1.4726838717415751,
 -0.36275739981030997,
 -0.26863220639739277,
 1.1903082915028236,
 -1.4451971240588577,
 -0.26863220639739277,
 0.3431815507865689,
 0.7196823244382377,
 0.24905635737365175,
 -0.5510077866361444,
 -1.6805101075911506,
 0.39024414749302755,
 1.0961830980899063,
 0.7196823244382377,
 1.143245694796365,
 1.3314960816221995,
 -0.8333833668748959,
 -1.162821543820106,
 -1.3510719306459404,
 1.4256212750351165,
 1.2373708882092822,
 1.049120501383448,
 0.5784945343188619,
 -1.6805101075911506,
 1.049120501383448,
 0.8138075178511549,
 -1.492259720765316,
 0.10786856725427597,
 -0.8804459635813545,
 -0.5510077866361444,
 -1.4451971240588577,
 1.707996855273868,
 1.378558678328658,
 0.6255571310253205,
 0.6255571310253205,
 1.5197464684480337,
 -0.45688259322322716,
 -1.3040093339394818,
 1.2373708882092822,
 -0.927508560287813,
 0.15493116396073456,
 1.378558678328658,
 0.6255571310253205,
 -1.633447510884692,
 -1.3040093339394818,
 1.613871661860951,
 -1.5393223174717747,
 0.5314319376124033,
 -1.2098841405265646,
 -0.17450701298447557,
 -0.8804459635813545,
 0.9549953079705307,
 1.4256212750351165,
 -1.5393223174717747,
 -0.7392581734619788,
 0.8608701145576134,
 1.4726838717415751,
 -1.3040093339394818,
 -1.0216337537007303,
 0.29611895408011035,
 0.20199376066719316,
 0.9549953079705307,
 1.0961830980899063,
 -1.0216337537007303,
 1.2373708882092822,
 -0.9745711569942717,
 0.4843693409059447,
 -0.5039451899296857,
 0.5314319376124033,
 -0.17450701298447557,
 0.8608701145576134,
 0.8138075178511549,
 0.3431815507865689,
 -0.7392581734619788,
 1.0020579046769893,
 -0.6921955767555201,
 1.2844334849157408,
 -1.162821543820106,
 -0.127444416278017,
 0.24905635737365175,
 1.049120501383448,
 -1.5393223174717747,
 1.0020579046769893,
 -1.492259720765316,
 1.049120501383448,
 0.39024414749302755,
 0.10786856725427597,
 -1.162821543820106,
 0.6255571310253205,
 -0.40981999651676854,
 0.013743373841358786,
 -1.4451971240588577,
 1.1903082915028236,
 -1.2098841405265646,
 -1.3510719306459404,
 1.378558678328658,
 -0.5980703833426029,
 1.6609342585674096,
 1.4726838717415751,
 -0.927508560287813,
 1.2373708882092822,
 -1.2569467372330232,
 -1.3040093339394818,
 -0.8333833668748959,
 -1.5863849141782334,
 1.5668090651544924,
 0.7667449211446963,
 -0.22156960969093417,
 -1.5393223174717747,
 -1.2569467372330232,
 1.049120501383448,
 0.8608701145576134,
 1.0961830980899063,
 -1.068696350407189,
 1.049120501383448,
 0.7196823244382377,
 0.3431815507865689,
 1.613871661860951,
 -1.3040093339394818,
 -0.03331922286509981,
 0.7667449211446963,
 -0.40981999651676854,
 1.6609342585674096,
 -0.5980703833426029,
 -1.6805101075911506,
 0.6255571310253205,
 1.4726838717415751,
 -1.4451971240588577,
 0.3431815507865689,
 1.049120501383448,
 -0.0803818195715584,
 -0.36275739981030997,
 1.0020579046769893,
 1.5197464684480337,
 -0.927508560287813,
 -0.927508560287813,
 1.5197464684480337,
 1.378558678328658,
 -1.1157589471136475,
 1.2373708882092822,
 -0.5980703833426029,
 0.7196823244382377,
 -0.5980703833426029,
 -1.6805101075911506,
 1.1903082915028236,
 0.060805970547817376,
 -1.633447510884692,
 1.0020579046769893,
 -1.068696350407189,
 -0.17450701298447557,
 0.7667449211446963,
 -0.9745711569942717,
 -0.22156960969093417,
 -1.3040093339394818,
 0.5314319376124033,
 -1.5393223174717747,
 -1.5863849141782334,
 -0.0803818195715584,
 -1.3510719306459404,
 -0.127444416278017,
 0.672619727731779,
 -0.40981999651676854,
 1.3314960816221995,
 0.7196823244382377,
 0.7196823244382377,
 -1.492259720765316,
 -1.633447510884692,
 -0.26863220639739277,
 0.5784945343188619,
 -1.2569467372330232,
 0.24905635737365175,
 0.10786856725427597,
 1.2844334849157408,
 -0.5039451899296857,
 -1.3510719306459404,
 0.4373067441994861,
 -0.9745711569942717,
 1.3314960816221995,
 -0.5510077866361444,
 -0.03331922286509981,
 1.2844334849157408,
 -0.17450701298447557,
 0.20199376066719316,
 0.060805970547817376,
 -0.5980703833426029,
 -1.5393223174717747,
 0.907932711264072,
 -1.2098841405265646,
 -1.633447510884692,
 0.15493116396073456,
 -1.5863849141782334,
 -0.31569480310385134,
 1.5668090651544924,
 1.0020579046769893,
 0.20199376066719316,
 -1.5393223174717747,
 -0.5980703833426029,
 0.15493116396073456,
 -1.492259720765316,
 -0.5510077866361444,
 -0.26863220639739277,
 0.3431815507865689,
 1.5197464684480337,
 -1.398134527352399,
 0.8138075178511549,
 0.5784945343188619,
 1.049120501383448,
 1.707996855273868,
 -1.3040093339394818,
 0.6255571310253205,
 -1.2569467372330232,
 0.6255571310253205,
 0.672619727731779,
 0.9549953079705307,
 -0.45688259322322716,
 -0.0803818195715584,
 0.907932711264072,
 0.8608701145576134,
 0.6255571310253205,
 -0.03331922286509981,
 0.907932711264072,
 -0.7392581734619788,
 -0.03331922286509981,
 -1.5863849141782334,
 -1.2098841405265646,
 -1.162821543820106,
 1.4726838717415751,
 -0.40981999651676854,
 1.707996855273868,
 -0.8804459635813545,
 0.907932711264072,
 1.613871661860951,
 -0.127444416278017,
 1.4726838717415751,
 0.4373067441994861,
 -0.6451329800490615,
 -1.1157589471136475,
 -1.1157589471136475,
 -0.22156960969093417,
 1.143245694796365,
 -0.45688259322322716,
 1.5668090651544924,
 1.707996855273868,
 0.20199376066719316,
 0.15493116396073456,
 1.049120501383448,
 0.39024414749302755,
 0.907932711264072,
 -0.6451329800490615,
 -0.45688259322322716,
 1.1903082915028236,
 0.10786856725427597,
 -1.633447510884692,
 -0.03331922286509981,
 1.049120501383448,
 1.5197464684480337,
 1.4256212750351165,
 -0.45688259322322716,
 -0.7863207701684373,
 -0.6451329800490615,
 0.5784945343188619,
 0.8138075178511549,
 1.5668090651544924,
 -0.8333833668748959,
 -0.8333833668748959,
 -0.5980703833426029,
 0.24905635737365175,
 0.15493116396073456,
 -1.162821543820106,
 1.4726838717415751,
 0.20199376066719316,
 -0.5980703833426029,
 0.9549953079705307,
 1.5668090651544924,
 0.4843693409059447,
 1.143245694796365,
 1.6609342585674096,
 1.4256212750351165,
 0.5784945343188619,
 0.15493116396073456,
 -1.0216337537007303,
 0.907932711264072,
 -1.492259720765316,
 -0.927508560287813,
 0.8138075178511549,
 -1.5393223174717747,
 0.7667449211446963,
 -0.5039451899296857,
 0.3431815507865689,
 0.15493116396073456,
 0.9549953079705307,
 -0.22156960969093417,
 -0.45688259322322716,
 -1.162821543820106,
 0.907932711264072,
 1.4256212750351165,
 -1.5393223174717747,
 1.3314960816221995,
 -0.40981999651676854,
 -1.398134527352399,
 0.672619727731779,
 1.1903082915028236,
 0.24905635737365175,
 1.378558678328658,
 1.143245694796365,
 0.9549953079705307,
 -0.8804459635813545,
 -1.6805101075911506,
 -0.17450701298447557,
 -0.22156960969093417,
 1.3314960816221995,
 -1.398134527352399,
 0.20199376066719316,
 1.3314960816221995,
 1.4726838717415751,
 -1.1157589471136475,
 -0.03331922286509981,
 -1.3510719306459404,
 -0.31569480310385134,
 1.1903082915028236,
 0.4843693409059447,
 0.20199376066719316,
 -1.492259720765316,
 -0.5510077866361444,
 1.0020579046769893,
 -1.633447510884692,
 1.4726838717415751,
 0.15493116396073456,
 1.2373708882092822,
 -0.45688259322322716,
 1.2373708882092822,
 1.6609342585674096,
 1.5668090651544924,
 -1.2098841405265646,
 -1.398134527352399,
 0.4843693409059447,
 1.143245694796365,
 -0.5980703833426029,
 -0.9745711569942717,
 0.15493116396073456,
 0.29611895408011035,
 -0.45688259322322716,
 0.5314319376124033,
 -0.40981999651676854,
 -0.7392581734619788,
 -0.5980703833426029,
 -0.17450701298447557,
 -0.45688259322322716,
 0.6255571310253205,
 -0.7392581734619788,
 1.6609342585674096,
 0.4843693409059447,
 1.5197464684480337,
 0.24905635737365175,
 1.613871661860951,
 -1.3040093339394818,
 1.707996855273868,
 1.3314960816221995,
 -0.7392581734619788,
 -1.492259720765316,
 0.5314319376124033,
 -0.26863220639739277,
 -0.9745711569942717,
 -0.7863207701684373,
 1.143245694796365,
 0.7667449211446963,
 0.6255571310253205,
 0.7196823244382377,
 -0.927508560287813,
 -1.162821543820106,
 0.672619727731779,
 -1.633447510884692,
 -0.22156960969093417,
 -1.633447510884692,
 -1.4451971240588577,
 -0.9745711569942717,
 1.378558678328658,
 1.4256212750351165,
 0.5784945343188619,
 0.3431815507865689,
 0.7667449211446963,
 -0.9745711569942717,
 1.6609342585674096,
 -0.8333833668748959,
 1.049120501383448,
 -1.068696350407189,
 -0.8804459635813545,
 0.20199376066719316,
 -1.5393223174717747,
 -1.492259720765316,
 -1.5393223174717747,
 -1.3510719306459404,
 1.143245694796365,
 -0.7392581734619788,
 -0.5039451899296857,
 0.907932711264072,
 0.4843693409059447,
 1.0961830980899063,
 -0.5510077866361444,
 0.24905635737365175,
 -1.6805101075911506,
 -0.31569480310385134,
 -1.633447510884692,
 -1.398134527352399,
 0.29611895408011035,
 0.20199376066719316,
 -1.4451971240588577,
 1.378558678328658,
 0.7196823244382377,
 1.6609342585674096,
 0.4373067441994861,
 -1.1157589471136475,
 -0.45688259322322716,
 0.013743373841358786,
 0.29611895408011035,
 -1.5863849141782334,
 -0.7863207701684373,
 -0.03331922286509981,
 -0.8333833668748959,
 -1.3040093339394818,
 -1.6805101075911506,
 0.6255571310253205,
 -0.5980703833426029,
 -1.5863849141782334,
 1.5668090651544924,
 0.9549953079705307,
 -0.17450701298447557,
 1.3314960816221995,
 -1.5863849141782334,
 1.2373708882092822,
 0.6255571310253205,
 0.29611895408011035,
 0.10786856725427597,
 0.013743373841358786,
 1.3314960816221995,
 0.24905635737365175,
 -0.03331922286509981,
 0.4373067441994861,
 1.4256212750351165,
 -1.492259720765316,
 1.0020579046769893,
 -0.5039451899296857,
 0.4373067441994861,
 -1.0216337537007303,
 0.10786856725427597,
 -0.6921955767555201,
 1.1903082915028236,
 1.0961830980899063,
 -0.0803818195715584,
 -0.40981999651676854,
 -1.6805101075911506,
 -0.36275739981030997,
 -1.6805101075911506,
 -0.9745711569942717,
 0.39024414749302755,
 1.4726838717415751,
 -0.40981999651676854,
 -1.3040093339394818,
 -0.5039451899296857,
 -0.0803818195715584,
 1.2373708882092822,
 0.5314319376124033,
 -1.068696350407189,
 -0.45688259322322716,
 -0.5510077866361444,
 -1.492259720765316,
 -0.6451329800490615,
 -1.5863849141782334,
 -0.6451329800490615,
 0.15493116396073456,
 0.9549953079705307,
 1.049120501383448,
 1.2373708882092822,
 0.7667449211446963,
 0.29611895408011035,
 1.707996855273868,
 0.4843693409059447,
 0.672619727731779,
 -0.17450701298447557,
 -1.5393223174717747,
 -1.492259720765316,
 1.143245694796365,
 0.4373067441994861,
 -0.6921955767555201,
 1.4256212750351165,
 -1.5393223174717747,
 -1.3510719306459404,
 0.29611895408011035,
 -1.3510719306459404,
 1.2844334849157408,
 -1.068696350407189,
 0.907932711264072,
 -1.6805101075911506,
 1.5197464684480337,
 0.5314319376124033,
 0.672619727731779,
 0.5314319376124033,
 0.060805970547817376,
 -0.8333833668748959,
 -0.40981999651676854,
 0.013743373841358786,
 -0.5980703833426029,
 -0.45688259322322716,
 -0.7863207701684373,
 1.0020579046769893,
 -0.03331922286509981,
 1.1903082915028236,
 1.2844334849157408,
 -0.5980703833426029,
 -0.9745711569942717,
 0.672619727731779,
 -0.31569480310385134,
 0.29611895408011035,
 1.613871661860951,
 0.8608701145576134,
 -1.492259720765316,
 -1.1157589471136475,
 -0.03331922286509981,
 0.4373067441994861,
 -1.5863849141782334,
 1.5197464684480337,
 -0.5510077866361444,
 -0.6451329800490615,
 -0.31569480310385134,
 0.3431815507865689,
 -1.0216337537007303,
 1.049120501383448,
 1.4726838717415751,
 1.3314960816221995,
 -0.7392581734619788,
 0.6255571310253205,
 -1.3040093339394818,
 -1.5863849141782334,
 -1.492259720765316,
 1.4256212750351165,
 -0.40981999651676854,
 -0.03331922286509981,
 1.5668090651544924,
 -0.26863220639739277,
 -1.633447510884692,
 -0.9745711569942717,
 -1.492259720765316,
 -1.162821543820106,
 0.24905635737365175,
 0.4843693409059447,
 1.143245694796365,
 -0.7863207701684373,
 -0.9745711569942717,
 -0.45688259322322716,
 -0.5510077866361444,
 0.013743373841358786,
 -0.40981999651676854,
 0.10786856725427597,
 -1.633447510884692,
 -0.8804459635813545,
 1.049120501383448,
 0.672619727731779,
 0.10786856725427597,
 -1.5863849141782334,
 -1.633447510884692,
 -1.1157589471136475,
 0.15493116396073456,
 1.4256212750351165,
 -1.5393223174717747,
 0.15493116396073456,
 -0.22156960969093417,
 1.2373708882092822,
 -0.927508560287813,
 1.613871661860951,
 0.4843693409059447,
 -1.5393223174717747,
 1.0020579046769893,
 1.1903082915028236,
 -1.633447510884692,
 -0.7392581734619788,
 1.143245694796365,
 -0.8333833668748959,
 0.7667449211446963,
 1.707996855273868,
 -0.17450701298447557,
 1.4256212750351165,
 -0.22156960969093417,
 -0.927508560287813,
 0.4843693409059447,
 -0.6451329800490615,
 1.6609342585674096,
 0.4843693409059447,
 -1.398134527352399,
 -1.3510719306459404,
 -0.8333833668748959,
 1.4726838717415751,
 0.060805970547817376,
 0.5314319376124033,
 1.6609342585674096,
 -0.5980703833426029,
 -0.127444416278017,

In [63]:
heartratedata.head()

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Smoking,Obesity,BMI,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk,BMI_cat,BPrank
0,67,0,208,158/88,72,0,1,0,31.251233,0,6,0,4,3
1,21,0,389,165/93,98,1,1,1,27.194973,1,7,0,3,4
2,21,1,324,174/99,72,1,0,0,28.176571,4,4,0,3,4
3,84,0,383,163/100,73,1,1,0,36.464704,3,4,0,4,4
4,66,0,318,91/88,93,1,1,1,21.809144,1,5,0,2,3

In [64]:
heartratedata.to_csv("cleaned.csv")